# Generated by Django 3.1.7 on 2023-01-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20221213_2325'),
    ]

    operations = [
        migrations.CreateModel(
            name='CMD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.CharField(max_length=500)),
            ],
        ),
    ]
